"""manifest.json — the single record every stage reads and writes.

Stage results are keyed by a fingerprint chain: each stage's fingerprint mixes in
its predecessor's, so re-running one stage with new params invalidates everything
downstream without any extra bookkeeping.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

from . import STAGES

# Bump a stage tag when that stage's logic changes in a way that invalidates its
# previous output. Downstream stages invalidate automatically via the chain.
STAGE_TAGS = {
    "fetch": "fetch/v1",
    "stems": "stems/v1",
    "transcript": "transcript/v39",
    "segments": "segments/v34",
    "translate": "translate/v31",
    # tts and timeline each received two independent changes in parallel (per-segment
    # tts_opts and lock-aware queueing; the media-end wall and lock-aware shortening),
    # so the tag moves past both claims of v13/v11 rather than picking one.
    "tts": "tts/v14",
    "timeline": "timeline/v12",
    "mix": "mix/v8",
    "report": "report/v1",
}

# Anything not listed here is dropped on save. This is what stops the segment
# record from growing back into the 30-field soup of the old pipeline.
SEGMENT_KEYS = {
    "id",
    "uid",        # stable identity across re-segmentation; see `mint_uid`
    "start",
    "end",
    "speaker",
    "text",
    "keep",
    "keep_reason",
    "lang",       # third-language keeps only: what the span's speech is, for subtitles
    "src_lang",   # editor override: this segment's source language (falls back to `lang`)
    "tgt_lang",   # editor override: translate this segment into something else
    "text_en",
    "text_mid",   # pivot runs only: the English intermediate text_en was made from
    "tts_opts",   # per-segment synthesis overrides (dubbing/ttsopts.py); user-set only
    "tts",
    "tts_opts",   # editor override: per-segment synthesis options (see dubbing.tts)
    "locked",     # {field: True} for fields the user edited by hand — see `is_locked`
    "place",
    # Editor-owned (editor/edits.py): human corrections that must survive a save.
    "tts_instructions",   # free-text style/emotion hint for the synthesiser
    "passthrough",        # speaker already speaks the target language: keep original
    "lang_override",      # per-segment target language, overriding source.tgt_lang
}

# Fields a user can lock. A locked field is never regenerated by a stage rerun:
# the user's edit outranks the pipeline (docs/APP_ARCHITECTURE.md, Non-negotiables).
# `text` and `speaker` have no generator to hold off, but the editor records them
# so a UI can show what was hand-edited.
LOCK_FIELDS = ("text", "text_en", "tts", "place", "keep", "speaker", "bounds")


def is_locked(seg: dict[str, Any], field: str) -> bool:
    """True when the user hand-edited `field` on this segment."""
    return bool((seg.get("locked") or {}).get(field))


def mint_uid(start: float, end: float, text: str) -> str:
    """The stable identity of a segment, derived from what created it.

    Opaque to every caller — the only promise is that it is stable. Content-derived
    rather than random on purpose: a run directory written before `uid` existed
    gets back-filled on load with exactly the uid a fresh re-segmentation would
    mint, so identity survives both the migration and a re-run that reproduces the
    same segment. Segments never overlap, so (start, end, text) is unique within a
    run; `ensure_uids` re-mints the rare duplicate anyway.

    Minted once, at creation, and then carried unchanged through every edit — a
    segment whose text the user rewrote keeps the uid its original text minted.
    """
    blob = f"{float(start):.3f}|{float(end):.3f}|{text or ''}"
    return "s" + hashlib.sha1(blob.encode("utf-8")).hexdigest()[:11]


def ensure_uids(segments: list[dict[str, Any]] | None) -> list[str]:
    """Give every segment a uid, keeping the ones already there. Returns those minted.

    Idempotent, so it is safe to call on load, on save, and at the end of the
    segments stage. A duplicate (a segment dict copied to make a trimmed piece)
    is re-minted from its own content, with a counter for the pathological case.
    """
    minted: list[str] = []
    seen: set[str] = set()
    for seg in segments or []:
        uid = seg.get("uid")
        if not uid or uid in seen:
            uid = mint_uid(seg.get("start", 0.0), seg.get("end", 0.0), seg.get("text", ""))
            n = 1
            while uid in seen:
                uid = mint_uid(seg.get("start", 0.0), seg.get("end", 0.0),
                               f"{seg.get('text', '')}#{n}")
                n += 1
            seg["uid"] = uid
            minted.append(uid)
        seen.add(uid)
    return minted


def new(source: dict[str, Any]) -> dict[str, Any]:
    return {
        "version": 1,
        "source": source,
        "files": {},
        "stages": {},
        "progress": {},
        "speakers": {},
        "segments": [],
        "outputs": {},
    }


def reset_stage(m: dict[str, Any], stage: str) -> None:
    """Drop what `stage` produced, so it can be recomputed from scratch.

    Stages also resume *within* themselves (per-segment), so this is only called
    when the stage's fingerprint changed — a resumed run keeps its partial work,
    a re-parameterised one does not.
    """
    if stage == "segments":
        m["segments"] = []
        m["speakers"] = {}
        return
    fields = {"translate": ("text_en", "text_mid"), "tts": ("tts",),
              "timeline": ("place",)}.get(stage)
    if not fields:
        return
    # Undo keep-flips this stage OR anything downstream of it made, so a rerun
    # re-decides them. Downstream flips must go too: a segment kept by tts_failed
    # still holds the translation that failed, and a translate reset that skips it
    # (because it looks "kept") re-feeds the same bad text to the new TTS run —
    # the downstream stage is guaranteed to rerun anyway once this one does.
    undo = {"translate": ("mt_failed", "tts_failed"), "tts": ("tts_failed",)}.get(stage, ())
    # A hand-edited field is not this stage's to discard: a global rerun must never
    # silently overwrite a human correction.
    lock = {"translate": "text_en", "tts": "tts", "timeline": "place"}[stage]
    for seg in m.get("segments") or []:
        if is_locked(seg, lock):
            continue
        if seg.get("keep_reason") in undo and not is_locked(seg, "keep"):
            seg["keep"], seg["keep_reason"] = False, None
        for field in fields:
            if (stage == "translate" and field == "text_en" and seg.get("keep")
                    and seg.get("keep_reason") != "foreign"):
                # Structurally kept segments are subtitled by the segments stage;
                # foreign keeps get their subtitle *from* translate, so theirs resets.
                continue
            seg.pop(field, None)


def load(workdir: Path) -> dict[str, Any] | None:
    path = workdir / "manifest.json"
    if not path.is_file():
        return None
    m = json.loads(path.read_text(encoding="utf-8"))
    # Migration: run dirs written before `uid` existed get theirs here, by the same
    # rule a fresh run would use, so the editor can key on it from the first load.
    ensure_uids(m.get("segments"))
    return m


def save(workdir: Path, m: dict[str, Any]) -> None:
    ensure_uids(m.get("segments"))
    for seg in m.get("segments") or []:
        for key in [k for k in seg if k not in SEGMENT_KEYS]:
            del seg[key]
    workdir.mkdir(parents=True, exist_ok=True)
    path = workdir / "manifest.json"
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(m, ensure_ascii=False, indent=1), encoding="utf-8")
    os.replace(tmp, path)


def stage_fingerprint(m: dict[str, Any], stage: str, params: dict[str, Any]) -> str:
    idx = STAGES.index(stage)
    upstream = ""
    if idx:
        upstream = (m.get("stages") or {}).get(STAGES[idx - 1], {}).get("fp", "")
    blob = json.dumps(
        {"tag": STAGE_TAGS[stage], "params": params, "up": upstream},
        sort_keys=True,
        ensure_ascii=False,
    )
    return hashlib.sha1(blob.encode("utf-8")).hexdigest()[:16]


def stage_done(
    m: dict[str, Any], workdir: Path, stage: str, fp: str, outputs: list[str]
) -> bool:
    rec = (m.get("stages") or {}).get(stage)
    if not rec or rec.get("fp") != fp:
        return False
    return all((workdir / o).exists() for o in outputs)


def mark_stage(m: dict[str, Any], stage: str, fp: str) -> None:
    m.setdefault("stages", {})[stage] = {"fp": fp}


def clear_stage(m: dict[str, Any], stage: str) -> None:
    """Force a full redo of `stage`, discarding even resumable partial work."""
    (m.get("stages") or {}).pop(stage, None)
    (m.get("progress") or {}).pop(stage, None)


def clear_downstream(m: dict[str, Any], stage: str) -> list[str]:
    """Invalidate every stage after `stage`. Returns the stages cleared.

    The fingerprint chain cannot do this on its own when a stage is re-run with
    unchanged parameters: `stage_fingerprint` mixes tag + params + upstream fp, all
    three unchanged, so the recomputed fingerprint matches — and translate/tts/
    timeline declare no output files, so `stage_done`'s `all([])` is True and they
    report "up to date". Re-running a stage genuinely does discard what came after
    it, so the record has to be dropped explicitly.
    """
    cleared = []
    for later in STAGES[STAGES.index(stage) + 1:]:
        clear_stage(m, later)
        reset_stage(m, later)
        cleared.append(later)
    return cleared
